package com.oconeco.spring_search_tempo.testfixtures

import java.io.OutputStream
import java.nio.file.FileSystems
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.Paths
import java.nio.file.StandardCopyOption
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream
import kotlin.io.path.createDirectories
import kotlin.io.path.outputStream

/**
 * Builds the canonical crawl fixture tree (issue #115) into a target
 * directory — typically a JUnit `@TempDir`.
 *
 * The fixture has two parts:
 *
 *  1. Static files committed under `src/test/resources/fixtures/crawl-tree/`.
 *     [build] copies the whole subtree into [target].
 *  2. Dynamic files generated on the fly: `oversized.txt` (just over the
 *     [TextExtractionService][com.oconeco.spring_search_tempo.base.service.TextExtractionService]
 *     max-extract limit) and `sample.zip` (3 mixed-extension entries).
 *     These are too bulky or too binary to commit; generating them keeps
 *     the repo clean and the intent explicit.
 *
 * Manifest constants on this object are the single source of truth — the
 * smoke test ([CrawlTreeFixtureTest]) asserts the built tree matches.
 */
object CrawlTreeFixture {

    const val CLASSPATH_ROOT: String = "fixtures/crawl-tree"

    /** File count committed under [CLASSPATH_ROOT] (including README.md). */
    const val STATIC_FILE_COUNT: Int = 18

    /** Directory count committed under [CLASSPATH_ROOT] (including the root itself). */
    const val STATIC_DIR_COUNT: Int = 11

    /**
     * Size in bytes of the generated `oversized.txt`. Set to one byte over
     * `TextExtractionService.MAX_STRING_LENGTH` (10 MiB) so the size-cap
     * branch is exercised deterministically.
     *
     * Kept as a literal here (not a reference to the production constant)
     * so changing the production cap forces an explicit fixture update —
     * tests should be intentional about what they're probing.
     */
    const val OVERSIZED_TXT_SIZE: Long = 10L * 1024L * 1024L + 1L

    /** Names of files generated by [build] (relative to [target]). */
    val GENERATED_FILES: List<String> = listOf("oversized.txt", "sample.zip")

    /** Entry names inside the generated `sample.zip`. */
    val ZIP_ENTRIES: List<String> = listOf("inside.txt", "Inside.kt", "inside.bin")

    /** Total file count in the built tree (static + generated). */
    const val BUILT_FILE_COUNT: Int = STATIC_FILE_COUNT + 2

    /**
     * Materialize the fixture tree into [target]. Returns [target] for
     * fluent use.
     *
     * If [target] is not empty, existing entries are left alone unless
     * they collide with copied/generated files (which are overwritten).
     */
    fun build(target: Path): Path {
        target.createDirectories()
        copyStatic(target)
        generateOversized(target.resolve("oversized.txt"))
        generateSampleZip(target.resolve("sample.zip"))
        return target
    }

    /**
     * Copy the committed subtree from the test classpath into [target].
     * Public so a consumer that wants only the static portion (without
     * the generated dynamic files) can opt in.
     */
    fun copyStatic(target: Path) {
        val source = resolveClasspathRoot()
        Files.walk(source).use { stream ->
            stream.forEach { src ->
                val rel = source.relativize(src).toString()
                val dst = if (rel.isEmpty()) target else target.resolve(rel)
                if (Files.isDirectory(src)) {
                    dst.createDirectories()
                } else {
                    dst.parent?.createDirectories()
                    Files.copy(src, dst, StandardCopyOption.REPLACE_EXISTING)
                }
            }
        }
    }

    private fun generateOversized(path: Path) {
        path.parent?.createDirectories()
        // Write a repeating ASCII pattern; content is irrelevant, size is
        // what matters. Stream in chunks to keep memory bounded.
        val chunk = "lorem ipsum dolor sit amet ".repeat(64).toByteArray()
        var remaining = OVERSIZED_TXT_SIZE
        path.outputStream().use { out: OutputStream ->
            while (remaining > 0) {
                val n = minOf(chunk.size.toLong(), remaining).toInt()
                out.write(chunk, 0, n)
                remaining -= n
            }
        }
    }

    private fun generateSampleZip(path: Path) {
        path.parent?.createDirectories()
        ZipOutputStream(path.outputStream()).use { zip ->
            zip.putNextEntry(ZipEntry("inside.txt"))
            zip.write("Plain text inside the archive.\n".toByteArray())
            zip.closeEntry()

            zip.putNextEntry(ZipEntry("Inside.kt"))
            zip.write("package archived\nfun main() = println(\"hi\")\n".toByteArray())
            zip.closeEntry()

            zip.putNextEntry(ZipEntry("inside.bin"))
            zip.write(byteArrayOf(0x00, 0x01, 0x02, 0x7F, 0x7E.toByte(), 0x00, 0x42))
            zip.closeEntry()
        }
    }

    /**
     * Resolve [CLASSPATH_ROOT] to a filesystem [Path]. Test resources are
     * exploded to disk by Gradle and IntelliJ, so the classpath URL has a
     * `file:` scheme and converts cleanly. If somebody packages tests
     * into a jar later, this will need to switch to `Files.walk` over a
     * `FileSystems.newFileSystem(jarUri)` view — for now the simple form
     * is correct and fast.
     */
    private fun resolveClasspathRoot(): Path {
        val url = Thread.currentThread().contextClassLoader.getResource(CLASSPATH_ROOT)
            ?: error("Classpath resource '$CLASSPATH_ROOT' not found. " +
                "Is src/test/resources/fixtures/crawl-tree/ on the test classpath?")
        val uri = url.toURI()
        return when (uri.scheme) {
            "file" -> Paths.get(uri)
            "jar" -> {
                val fs = runCatching { FileSystems.getFileSystem(uri) }
                    .getOrElse { FileSystems.newFileSystem(uri, emptyMap<String, Any>()) }
                fs.getPath(CLASSPATH_ROOT)
            }
            else -> error("Unsupported classpath URI scheme: ${uri.scheme} ($uri)")
        }
    }
}
