apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://host.docker.internal:9090   # Prometheus runs on the host network
    isDefault: true
    editable: false
