package com.oconeco.spring_search_tempo.base.domain

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.EntityListeners
import jakarta.persistence.FetchType
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.JoinColumn
import jakarta.persistence.ManyToOne
import jakarta.persistence.OneToMany
import jakarta.persistence.SequenceGenerator
import jakarta.persistence.Table
import java.time.OffsetDateTime
import org.hibernate.annotations.JdbcTypeCode
import org.hibernate.type.SqlTypes
import org.springframework.data.annotation.CreatedDate
import org.springframework.data.annotation.LastModifiedDate
import org.springframework.data.jpa.domain.support.AuditingEntityListener


@Entity
@Table(name = "content_chunks")
@EntityListeners(AuditingEntityListener::class)
class ContentChunk {

    @Id
    @Column(
        nullable = false,
        updatable = false
    )
    @SequenceGenerator(
        name = "primary_sequence",
        sequenceName = "primary_sequence",
        allocationSize = 1,
        initialValue = 10000
    )
    @GeneratedValue(
        strategy = GenerationType.SEQUENCE,
        generator = "primary_sequence"
    )
    var id: Long? = null

    @Column(nullable = false)
    var chunkNumber: Int? = null

    @Column
    var chunkType: String? = null

    @Column
    var createdAt: OffsetDateTime? = null

    @Column
    var endPosition: Long? = null

    /**
     * PostgreSQL tsvector for full-text search.
     *
     * This field is automatically generated by PostgreSQL using a GENERATED ALWAYS AS expression.
     * For ContentChunk, the search vector is generated from the chunk's text content only.
     *
     * IMPORTANT: Do not modify this field directly - it is managed by the database.
     *
     * NOTE: ContentChunk entities are typically created from large documents to enable granular search.
     *       Each chunk should be kept under 250KB to avoid tsvector size limits.
     *       See FSFile.ftsVector for details on handling large documents.
     */
    @Column(
        name = "fts_vector",
        columnDefinition = """
        tsvector GENERATED ALWAYS AS (
            to_tsvector('english', coalesce(text, ''))
        ) STORED
        """,
        insertable = false,
        updatable = false
    )
    @JdbcTypeCode(SqlTypes.OTHER)
    var ftsVector: ByteArray? = null

    @Column
    var lastModifiedDate: OffsetDateTime? = null

    @Column(columnDefinition = "text")
    var namedEntities: String? = null

    @Column(columnDefinition = "text")
    var nouns: String? = null

    @Column
    var parentType: String? = null

    @Column
    var startPosition: Long? = null

    @Column(
        nullable = false,
        columnDefinition = "text"
    )
    var text: String? = null

    @Column(columnDefinition = "text")
    var tokenAnnotations: String? = null

    @Column
    var vectorEmbedding: String? = null

    @Column(columnDefinition = "text")
    var verbs: String? = null

    @Column
    var solrIndexedAt: OffsetDateTime? = null

    @Column
    var textLength: Long? = null

    @Column(columnDefinition = "text")
    var userAnnotations: String? = null

    @Column
    var status: String? = null

    @Column(columnDefinition = "text")
    var parseNpvp: String? = null

    @Column(columnDefinition = "text")
    var parseUd: String? = null

    @Column(columnDefinition = "text")
    var parseTree: String? = null

    @Column(columnDefinition = "text")
    var conllu: String? = null

    @Column
    var sentiment: String? = null  // POSITIVE, NEGATIVE, NEUTRAL

    @Column
    var sentimentScore: Double? = null  // 0.0 to 1.0

    @Column
    var nlpProcessedAt: OffsetDateTime? = null  // Timestamp of NLP processing

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parent_chunk_id")
    var parentChunk: ContentChunk? = null

    @OneToMany(mappedBy = "parentChunk")
    var childChunks = mutableSetOf<ContentChunk>()

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "concept_id")
    var concept: FSFile? = null

    /**
     * Email message parent (alternative to FSFile concept).
     * A ContentChunk belongs to either an FSFile OR an EmailMessage, not both.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "email_message_id")
    var emailMessage: EmailMessage? = null

    @CreatedDate
    @Column(
        nullable = false,
        updatable = false
    )
    var dateCreated: OffsetDateTime? = null

    @LastModifiedDate
    @Column(nullable = false)
    var lastUpdated: OffsetDateTime? = null

}
