package com.oconeco.spring_search_tempo.base.domain

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.FetchType
import jakarta.persistence.JoinColumn
import jakarta.persistence.ManyToOne
import jakarta.persistence.OneToMany
import org.hibernate.annotations.JdbcTypeCode
import org.hibernate.type.SqlTypes
import java.time.OffsetDateTime


/**
 * Individual email message with envelope data, content, and metadata.
 *
 * Stores extracted email content for full-text search and optional chunking.
 * Linked to ContentChunk for sentence-level analysis (same pattern as FSFile).
 */
@Entity
class EmailMessage : SaveableObject() {

    // Email identifiers
    @Column(unique = true, columnDefinition = "text")
    var messageId: String? = null  // RFC 5322 Message-ID header (globally unique)

    @Column
    var imapUid: Long? = null  // IMAP UID (folder-specific, for incremental sync)

    // Envelope data
    @Column(columnDefinition = "text")
    var subject: String? = null

    @Column(columnDefinition = "text")
    var fromAddress: String? = null

    @Column(columnDefinition = "text")
    var toAddresses: String? = null  // JSON array

    @Column(columnDefinition = "text")
    var ccAddresses: String? = null  // JSON array

    @Column(columnDefinition = "text")
    var bccAddresses: String? = null  // JSON array

    @Column
    var sentDate: OffsetDateTime? = null

    @Column
    var receivedDate: OffsetDateTime? = null

    // Content
    @Column(columnDefinition = "text")
    var bodyText: String? = null  // Extracted plain text (for search and chunking)

    @Column
    var bodySize: Long? = null

    @Column(columnDefinition = "text")
    var bodyHtml: String? = null  // Original HTML (optional, for display)

    // Email metadata
    @Column(columnDefinition = "text")
    var contentType: String? = null

    @Column
    var hasAttachments: Boolean = false

    @Column
    var attachmentCount: Int = 0

    @Column(columnDefinition = "text")
    var attachmentNames: String? = null  // JSON array

    // Threading
    @Column(columnDefinition = "text")
    var inReplyTo: String? = null  // Message-ID being replied to

    @Column(columnDefinition = "text")
    var threadReferences: String? = null  // Thread references (JSON array of Message-IDs)

    @Column(columnDefinition = "text")
    var threadId: String? = null  // Computed thread identifier

    /**
     * PostgreSQL tsvector for full-text search.
     *
     * Automatically generated by PostgreSQL using weighted search vectors:
     * - Weight A (highest): subject
     * - Weight B: from_address, to_addresses
     * - Weight C: body_text (limited to first 250,000 characters)
     *
     * IMPORTANT: Do not modify this field directly - it is managed by the database.
     */
    @Column(
        name = "fts_vector",
        columnDefinition = """
        tsvector GENERATED ALWAYS AS (
            setweight(to_tsvector('english', coalesce(subject, '')), 'A') ||
            setweight(to_tsvector('english', coalesce(from_address, '')), 'B') ||
            setweight(to_tsvector('english', coalesce(to_addresses, '')), 'B') ||
            setweight(to_tsvector('english', coalesce(substring(body_text, 1, 250000), '')), 'C')
        ) STORED
        """,
        insertable = false,
        updatable = false
    )
    @JdbcTypeCode(SqlTypes.OTHER)
    var ftsVector: ByteArray? = null

    // Relationships
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "email_account_id")
    var emailAccount: EmailAccount? = null

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "email_folder_id")
    var emailFolder: EmailFolder? = null

    @OneToMany(mappedBy = "emailMessage")
    var contentChunks: MutableSet<ContentChunk> = mutableSetOf()

}
