package com.oconeco.spring_search_tempo.base.domain

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.FetchType
import jakarta.persistence.JoinColumn
import jakarta.persistence.ManyToOne
import jakarta.persistence.OneToMany
import org.hibernate.annotations.JdbcTypeCode
import org.hibernate.type.SqlTypes


@Entity
class FSFile : FSObject() {

    @Column(columnDefinition = "text")
    var bodyText: String? = null

    @Column
    var bodySize: Long? = null

    // Document metadata fields (extracted by Tika)
    @Column(columnDefinition = "text")
    var author: String? = null

    @Column(columnDefinition = "text")
    var title: String? = null

    @Column(columnDefinition = "text")
    var subject: String? = null

    @Column(columnDefinition = "text")
    var keywords: String? = null

    @Column(columnDefinition = "text")
    var comments: String? = null

    @Column(columnDefinition = "text")
    var creationDate: String? = null

    @Column(columnDefinition = "text")
    var modifiedDate: String? = null

    @Column(columnDefinition = "text")
    var language: String? = null

    @Column(columnDefinition = "text")
    var contentType: String? = null

    @Column
    var pageCount: Int? = null

    @OneToMany(mappedBy = "concept")
    var contentChunk = mutableSetOf<ContentChunks>()

    /**
     * PostgreSQL tsvector for full-text search.
     *
     * This field is automatically generated by PostgreSQL using a GENERATED ALWAYS AS expression.
     * The expression creates weighted search vectors from document metadata and content:
     * - Weight A (highest): title
     * - Weight B: author, subject, keywords
     * - Weight C: body_text (limited to first 250,000 characters to stay within 1MB tsvector limit)
     * - Weight D (lowest): label
     *
     * IMPORTANT: Do not modify this field directly - it is managed by the database.
     *
     * TODO: Implement chunking strategy for documents with body_text > 1MB
     *       Currently, only the first ~250K characters are indexed. For complete indexing
     *       of large documents, implement:
     *       1. Split large body_text into overlapping chunks in ContentChunks table
     *       2. Index each chunk's fts_vector separately
     *       3. Aggregate search results across all chunks for the file
     *       See: docs/guides/fts-large-document-chunking.md (to be created)
     */
    @Column(
        name = "fts_vector",
        columnDefinition = """
        tsvector GENERATED ALWAYS AS (
            setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
            setweight(to_tsvector('english', coalesce(author, '')), 'B') ||
            setweight(to_tsvector('english', coalesce(subject, '')), 'B') ||
            setweight(to_tsvector('english', coalesce(keywords, '')), 'B') ||
            setweight(to_tsvector('english', coalesce(substring(body_text, 1, 250000), '')), 'C') ||
            setweight(to_tsvector('english', coalesce(label, '')), 'D')
        ) STORED
        """,
        insertable = false,
        updatable = false
    )
    @JdbcTypeCode(SqlTypes.OTHER)
    var ftsVector: ByteArray? = null

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fs_folder_id")
    var fsFolder: FSFolder? = null

}
