package com.oconeco.spring_search_tempo.base.domain

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.FetchType
import jakarta.persistence.Index
import jakarta.persistence.JoinColumn
import jakarta.persistence.ManyToOne
import jakarta.persistence.OneToMany
import jakarta.persistence.Table
import org.hibernate.annotations.JdbcTypeCode
import org.hibernate.type.SqlTypes


@Entity
@Table(
    indexes = [
        Index(name = "idx_status", columnList = "status"),
    ]
)
class FSFile : FSObject() {

    @Column(columnDefinition = "text")
    var bodyText: String? = null

    @Column
    var bodySize: Long? = null

    // Document metadata fields (extracted by Tika)
    @Column(columnDefinition = "text")
    var author: String? = null

    @Column(columnDefinition = "text")
    var title: String? = null

    @Column(columnDefinition = "text")
    var subject: String? = null

    @Column(columnDefinition = "text")
    var keywords: String? = null

    @Column(columnDefinition = "text")
    var comments: String? = null

    @Column(columnDefinition = "text")
    var creationDate: String? = null

    @Column(columnDefinition = "text")
    var modifiedDate: String? = null

    @Column(columnDefinition = "text")
    var language: String? = null

    @Column(columnDefinition = "text")
    var contentType: String? = null

    @Column
    var pageCount: Int? = null

    /**
     * Timestamp when this file was last chunked into ContentChunks.
     * Used to determine if re-chunking is needed (when lastUpdated > chunkedAt).
     */
    @Column
    var chunkedAt: java.time.OffsetDateTime? = null

    /**
     * When Tika text extraction was performed.
     * Used for progressive analysis: files with analysisStatus >= INDEX
     * but indexedAt = null need text extraction.
     */
    @Column
    var indexedAt: java.time.OffsetDateTime? = null

    /**
     * Stores Tika extraction error message if text extraction failed.
     * Allows distinguishing between "not yet indexed" (indexedAt=null, indexError=null)
     * and "failed to index" (indexedAt=timestamp, indexError=message).
     */
    @Column(columnDefinition = "text")
    var indexError: String? = null

    /**
     * JSON metadata for archive files (zip, tar, rar, 7z, etc.).
     * Stores entry names/sizes without extracting full contents.
     * Example: [{"name": "file1.txt", "size": 1234}, {"name": "dir/file2.txt", "size": 5678}]
     * This allows search by archive contents without expensive extraction.
     */
    @Column(columnDefinition = "jsonb")
    @JdbcTypeCode(SqlTypes.JSON)
    var archiveContents: String? = null

    @OneToMany(mappedBy = "concept")
    var contentChunks = mutableSetOf<ContentChunk>()

    /**
     * PostgreSQL tsvector for full-text search.
     *
     * This field is automatically generated by PostgreSQL using a GENERATED ALWAYS AS expression.
     * The expression creates weighted search vectors from document metadata and content:
     * - Weight A (highest): title
     * - Weight B: author, subject, keywords
     * - Weight C: body_text (limited to first 250,000 characters to stay within 1MB tsvector limit)
     * - Weight D (lowest): label
     *
     * IMPORTANT: Do not modify this field directly - it is managed by the database.
     *
     * TODO: Implement chunking strategy for documents with body_text > 1MB
     *       Currently, only the first ~250K characters are indexed. For complete indexing
     *       of large documents, implement:
     *       1. Split large body_text into overlapping chunks in ContentChunk table
     *       2. Index each chunk's fts_vector separately
     *       3. Aggregate search results across all chunks for the file
     *       See: docs/guides/fts-large-document-chunking.md (to be created)
     */
    @Column(
        name = "fts_vector",
        columnDefinition = """
        tsvector GENERATED ALWAYS AS (
            setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
            setweight(to_tsvector('english', coalesce(author, '')), 'B') ||
            setweight(to_tsvector('english', coalesce(subject, '')), 'B') ||
            setweight(to_tsvector('english', coalesce(keywords, '')), 'B') ||
            setweight(to_tsvector('english', coalesce(substring(body_text, 1, 250000), '')), 'C') ||
            setweight(to_tsvector('english', coalesce(label, '')), 'D')
        ) STORED
        """,
        insertable = false,
        updatable = false
    )
    @JdbcTypeCode(SqlTypes.OTHER)
    var ftsVector: ByteArray? = null

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "fs_folder_id")
    var fsFolder: FSFolder? = null

}
