package com.oconeco.spring_search_tempo.base.domain

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.EnumType
import jakarta.persistence.Enumerated
import jakarta.persistence.FetchType
import jakarta.persistence.JoinColumn
import jakarta.persistence.ManyToOne
import jakarta.persistence.OneToMany
import org.hibernate.annotations.JdbcTypeCode
import org.hibernate.type.SqlTypes
import java.time.OffsetDateTime


/**
 * Individual file or folder synced from OneDrive via Microsoft Graph API.
 *
 * Items are identified by their stable Graph item ID (not path, which can change).
 * Supports two-pass sync: metadata first (from delta API), then content download.
 */
@Entity
class OneDriveItem : SaveableObject() {

    // Graph item identity (stable across renames/moves)
    @Column(nullable = false, columnDefinition = "text")
    var graphItemId: String? = null

    @Column(columnDefinition = "text")
    var parentGraphItemId: String? = null

    @Column(nullable = false, columnDefinition = "text")
    var driveId: String? = null

    // Item metadata
    @Column(columnDefinition = "text")
    var itemName: String? = null

    @Column(columnDefinition = "text")
    var itemPath: String? = null

    @Column(columnDefinition = "text")
    var mimeType: String? = null

    @Column(nullable = false)
    var isFolder: Boolean = false

    @Column(nullable = false)
    var isDeleted: Boolean = false

    @Column(columnDefinition = "text")
    var fileHash: String? = null

    @Column(columnDefinition = "text")
    var hashAlgorithm: String? = null

    // Graph timestamps
    @Column
    var graphCreatedAt: OffsetDateTime? = null

    @Column
    var graphModifiedAt: OffsetDateTime? = null

    // Content (populated by Pass 2 - content download)
    @Column(columnDefinition = "text")
    var bodyText: String? = null

    @Column
    var bodySize: Long? = null

    @Column(columnDefinition = "text")
    var contentType: String? = null

    @Column(columnDefinition = "text")
    var author: String? = null

    @Column(columnDefinition = "text")
    var title: String? = null

    @Column
    var pageCount: Int? = null

    // Processing state
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    var fetchStatus: OneDriveFetchStatus = OneDriveFetchStatus.METADATA_ONLY

    @Column
    var chunkedAt: OffsetDateTime? = null

    /**
     * PostgreSQL tsvector for full-text search.
     *
     * Automatically generated by PostgreSQL using weighted search vectors:
     * - Weight A (highest): title, item_name
     * - Weight B: author
     * - Weight C: body_text (limited to first 250,000 characters)
     * - Weight D: item_path
     *
     * IMPORTANT: Do not modify this field directly - it is managed by the database.
     */
    @Column(
        name = "fts_vector",
        columnDefinition = """
        tsvector GENERATED ALWAYS AS (
            setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
            setweight(to_tsvector('english', coalesce(item_name, '')), 'A') ||
            setweight(to_tsvector('english', coalesce(author, '')), 'B') ||
            setweight(to_tsvector('english', coalesce(substring(body_text, 1, 250000), '')), 'C') ||
            setweight(to_tsvector('english', coalesce(item_path, '')), 'D')
        ) STORED
        """,
        insertable = false,
        updatable = false
    )
    @JdbcTypeCode(SqlTypes.OTHER)
    var ftsVector: ByteArray? = null

    // Relationships
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "one_drive_account_id", nullable = false)
    var oneDriveAccount: OneDriveAccount? = null

    @OneToMany(mappedBy = "oneDriveItem")
    var contentChunks: MutableSet<ContentChunk> = mutableSetOf()

}
