package com.oconeco.spring_search_tempo.base.model

import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Size
import java.time.OffsetDateTime
import org.springframework.format.annotation.DateTimeFormat


class ContentChunkDTO {

    var id: Long? = null

    @NotNull
    var chunkNumber: Int? = null

    @Size(max = 255)
    var chunkType: String? = null

    @DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm:ssXXX")
    var createdAt: OffsetDateTime? = null

    var endPosition: Long? = null

    @DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm:ssXXX")
    var lastModifiedDate: OffsetDateTime? = null

    var namedEntities: String? = null

    var nouns: String? = null

    @Size(max = 255)
    var parentType: String? = null

    var startPosition: Long? = null

    @NotNull
    var text: String? = null

    /**
     * PostgreSQL tsvector for full-text search (read-only).
     * Auto-generated by database. Included for search ranking/debugging.
     * Ignored when mapping DTO→Entity (see ContentChunkMapper).
     */
    var ftsVector: ByteArray? = null

    var tokenAnnotations: String? = null

    /**
     * Vector embedding as float array (1024 dimensions for mxbai-embed-large).
     * Null when embedding hasn't been generated yet.
     */
    var embedding: FloatArray? = null

    /**
     * Timestamp when embedding was generated.
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm:ssXXX")
    var embeddingGeneratedAt: OffsetDateTime? = null

    /**
     * Name of the embedding model used.
     */
    @Size(max = 100)
    var embeddingModel: String? = null

    var verbs: String? = null

    @DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm:ssXXX")
    var solrIndexedAt: OffsetDateTime? = null

    var textLength: Long? = null

    var userAnnotations: String? = null

    @Size(max = 255)
    var status: String? = null

    var parseNpvp: String? = null

    var parseUd: String? = null

    var parseTree: String? = null

    var conllu: String? = null

    @Size(max = 50)
    var sentiment: String? = null

    var sentimentScore: Double? = null

    @DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm:ssXXX")
    var nlpProcessedAt: OffsetDateTime? = null

    var parentChunk: Long? = null

    var concept: Long? = null

    /**
     * Email message parent (alternative to FSFile concept).
     * A ContentChunk belongs to either an FSFile OR an EmailMessage, not both.
     */
    var emailMessage: Long? = null

    /**
     * OneDrive item parent (alternative to FSFile/EmailMessage/BrowserBookmark).
     * A ContentChunk belongs to exactly one of: FSFile, EmailMessage, BrowserBookmark, or OneDriveItem.
     */
    var oneDriveItem: Long? = null

}
